[package]
name = "fdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.11.1"
parking_lot = "0.12.1"
thiserror = "1.0.57"
bytes = "1.5.0"
